### ISSUE TITLE
Compile list of all desired sensors

### ISSUE THREAD

**Issue by MellingJJ** [CameronLR/FS_DAQ_System#1]
Ideally before work starts on programming the `Teensy` all sensors that are wanted should be specified.

In specifying all the sensors desired the following should be documented:
 - Sensor Component
 - Sensor Communication Protocol (ADC/I2C/SPI/UART)
 - Sensor Desired Logging Frequency
 - Teensy Pin Connection
 - Any external circuitry needed (e.g. multiplexer)

This information can be stored inside the wiki

**Comment by CameronLR** [comment]
Looks good, I'll try to make a start on this
